### ISSUE TITLE
Rust nightly does not seem to work with pgrx 0.8.4

### ISSUE THREAD

**Issue by craigpastro** [supabase/pg_jsonschema#30]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

So I started out just trying to do a `docker compose up`. It resulted in the following error:
```
...
#0 3.472    Compiling cc v1.0.79
#0 3.496    Compiling autocfg v1.1.0#0 3.530 error[E0635]: unknown feature `proc_macro_span_shrink`
#0 3.530   --> /home/supa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.58/src/lib.rs:92:30
#0 3.530    |
#0 3.530 92 |     feature(proc_macro_span, proc_macro_span_shrink)
#0 3.530    |                              ^^^^^^^^^^^^^^^^^^^^^^
#0 3.530
#0 3.590 For more information about this error, try `rustc --explain E0635`.
#0 3.596 error: could not compile `proc-macro2` (lib) due to previous error
#0 3.597 warning: build failed, waiting for other jobs to finish...
#0 4.384 error: failed to compile `cargo-pgrx v0.8.4`, intermediate artifacts can be found at `/tmp/cargo-installVOhPgA`.
#0 4.384 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
------
failed to solve: process "/bin/sh -c cargo install cargo-pgrx --version 0.8.4 --locked" did not complete successfully: exit code: 101
```

I tried using the stable toolchain and also to bump the version of pgrx. Both of these resulted in a docker error:
```
 => => #    Compiling num-cmp v0.1.0
 => => #    Compiling seahash v4.1.0
 => => #    Compiling jsonschema v0.16.1
 => => #    Compiling pgrx v0.8.4
failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
```

So then I just tried to `cargo local-install --locked cargo-pgrx --version "0.8.4"` which failed with the first error. Then I tried switching to the stable toolchain and it was all good.

Anyway, I think the point is that the version of pgrx needs to be bumped for the `Dockerfile` to work. Although, for some reason I could not get it to work with the version of Docker that I have installed. It did work on a different computer (Intel Mac) with an older version of Docker 🤷 

Edit: I'm happy to play around and make a PR if you would like to bump the version of pgrx. I am also trying to get Docker to work with my extension and I was essentially copying your Dockerfile 😛 

## To Reproduce

- `docker compose up`

## Expected behavior

A Postgres contain with pg_jsonschema starts up.

## System information

- OS: macOS with M2 Pro chip
- Docker version: 4.20.1
